Use base64.encodebytes() instead of encodestring()
This fixes an error on python 3.9:
  AttributeError: module 'base64' has no attribute 'encodestring'

base64.encodestring() is deprecated since 3.9:
https://docs.python.org/3.8/library/base64.html#base64.encodestring